# 1.8 Rappel d'algèbre linéaire
- Opérations vectorielles
- Multiplication
    - Multiplication vecteur-vecteur
    - Multiplication matrice-vecteur
    - Multiplication matrice-matrice
- Matrice identité
-Inverse

In [1]:
import numpy as np

## Opérations vectorielles

In [2]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [3]:
# addition 
print(u + v)

# subtraction 
print(u - v)

# scalar multiplication 
print(2 * v)

[ 5 11 13 12]
[-1  3 -3  0]
[ 6  8 16 12]


## Multiplication

### Multiplication vecteur-vecteur

In [4]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [5]:
 print(vector_vector_multiplication(u, v))

110.0


### Multiplication matrice-vecteur

In [6]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]

    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [7]:
U = np.array([[2, 7, 5, 6],[3, 4, 8, 6], [3, 4, 8, 6], [3, 4, 8, 6]])
V = v.reshape(4, 1)

matrix_vector_multiplication(U, V)

/tmp/ipykernel_24933/1754765005.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  result[i] = vector_vector_multiplication(U[i], v)


array([110., 125., 125., 125.])

# Multiplication matrice-matrice

In [8]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [9]:
matrix_matrix_multiplication(U, U)


array([[ 58.,  86., 154., 120.],
       [ 60.,  93., 159., 126.],
       [ 60.,  93., 159., 126.],
       [ 60.,  93., 159., 126.]])

## Matrice d'identité

In [10]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Inverse

In [11]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])
inv = np.linalg.inv(V)
inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])