# 1.8 Rappel d'algèbre linéaire
- Opérations vectorielles
- Multiplication
    - Multiplication vecteur-vecteur
    - Multiplication matrice-vecteur
    - Multiplication matrice-matrice
- Matrice identité
-Inverse

In [3]:
import numpy as np

## Opérations vectorielles

In [11]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [5]:
# addition 
print(u + v)

# subtraction 
print(u - v)

# scalar multiplication 
print(2 * v)

[ 5 11 13 12]
[-1  3 -3  0]
[ 6  8 16 12]


## Multiplication

### Multiplication vecteur-vecteur

In [6]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [12]:
 print(vector_vector_multiplication(u, v))

110.0


### Multiplication matrice-vecteur

In [41]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]

    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [42]:
U = np.array([[2, 7, 5, 6],[3, 4, 8, 6], [3, 4, 8, 6], [3, 4, 8, 6]])
V = v.reshape(4, 1)

matrix_vector_multiplication(U, V)

/tmp/ipykernel_10631/1754765005.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  result[i] = vector_vector_multiplication(U[i], v)


array([110., 125., 125., 125.])

# Multiplication matrice-matrice

In [43]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [46]:
matrix_matrix_multiplication(U, U)


array([[ 58.,  86., 154., 120.],
       [ 60.,  93., 159., 126.],
       [ 60.,  93., 159., 126.],
       [ 60.,  93., 159., 126.]])

In [37]:
matrix_matrix_multiplication(U, V)

array([[110.],
       [125.]])

In [2]:
!git add linear-algebra.ipynb
!git commit -m "linear algebra resume"
!git push

[main 7548513] linear algebra resume
 Committer: georgesmbock <mbock@DESKTOP-3KEOBHU>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:

    git config --global user.name "Your Name"
    git config --global user.email you@example.com

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 32 insertions(+), 5 deletions(-)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 1.41 KiB | 1.41 MiB/s, done.
Total 4 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/georgesmbock/zoomcamp-ML-2025-home-work.git
   32a5f27..7548513  main -> main
