## Introduction to Numpy

Plan:

- Creating arrays
- Multi-dimensensionnal arrays
- Randonly generated arrays
- Element-wise operations
    - Comparaison operations
    - Logical operational
- Summamaring operations

In [1]:
import numpy as np

### Creating arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
l = [1, 2, 3]
arr = np.array(l)

arr

array([1, 2, 3])

In [6]:
arr[:,]

array([1, 2, 3])

In [7]:
arr[1:3]

array([2, 3])

In [8]:
arr[-1]

np.int64(3)

In [9]:
arr[-2]

np.int64(2)

In [10]:
arr[-3]

np.int64(1)

In [11]:
arr[-3:-1]

array([1, 2])

In [12]:
arr[2] = 10
arr

array([ 1,  2, 10])

In [13]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3)

array([0, 1, 2])

In [15]:
np.linspace(2, 5, 3)

array([2. , 3.5, 5. ])

### Multi-dimentional array

In [16]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([
    [ 1,  2, 10],
    [ 1,  2, 10],
    [ 1,  2, 10]
])

n

array([[ 1,  2, 10],
       [ 1,  2, 10],
       [ 1,  2, 10]])

In [18]:
n[:,]

array([[ 1,  2, 10],
       [ 1,  2, 10],
       [ 1,  2, 10]])

In [19]:
n[:]

array([[ 1,  2, 10],
       [ 1,  2, 10],
       [ 1,  2, 10]])

In [20]:
n[2:,]

array([[ 1,  2, 10]])

In [21]:
n[:,2]

array([10, 10, 10])

In [22]:
n[:2]

array([[ 1,  2, 10],
       [ 1,  2, 10]])

In [23]:
n[:,1:]

array([[ 2, 10],
       [ 2, 10],
       [ 2, 10]])

In [24]:
n[1:2,2]

array([10])

### Randomly generated arrays

In [25]:
np.random.seed(2)

In [26]:
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [27]:
np.random.rand(2, 3)

array([[0.62113383, 0.52914209, 0.13457995],
       [0.51357812, 0.18443987, 0.78533515]])

In [28]:
np.random.rand(3, 3, 1)

array([[[0.85397529],
        [0.49423684],
        [0.84656149]],

       [[0.07964548],
        [0.50524609],
        [0.0652865 ]],

       [[0.42812233],
        [0.09653092],
        [0.12715997]]])

In [29]:
np.random.rand(3, 3, 2)

array([[[0.59674531, 0.226012  ],
        [0.10694568, 0.22030621],
        [0.34982629, 0.46778748]],

       [[0.20174323, 0.64040673],
        [0.48306984, 0.50523672],
        [0.38689265, 0.79363745]],

       [[0.58000418, 0.1622986 ],
        [0.70075235, 0.96455108],
        [0.50000836, 0.88952006]]])

In [30]:
np.random.rand(3, 3, 3)

array([[[0.34161365, 0.56714413, 0.42754596],
        [0.43674726, 0.77655918, 0.53560417],
        [0.95374223, 0.54420816, 0.08209492]],

       [[0.3663424 , 0.8508505 , 0.40627504],
        [0.02720237, 0.24717724, 0.06714437],
        [0.99385201, 0.97058031, 0.80025835]],

       [[0.60181712, 0.76495986, 0.16922545],
        [0.29302323, 0.52406688, 0.35662428],
        [0.04567897, 0.98315345, 0.44135492]]])

In [31]:
np.random.randn(3, 3, 1)

array([[[-2.04032305],
        [ 0.04625552],
        [-0.67767558]],

       [[-1.43943903],
        [ 0.52429643],
        [ 0.73527958]],

       [[-0.65325027],
        [ 0.84245628],
        [-0.38151648]]])

In [32]:
np.random.randint(low=3, high=5, size=(5, 2))

array([[3, 3],
       [4, 4],
       [3, 3],
       [4, 4],
       [4, 4]])

### Element-wise operations

In [33]:
a = np.arange(5)

a

array([0, 1, 2, 3, 4])

In [34]:
a + 1

array([1, 2, 3, 4, 5])

In [35]:
a * 2

array([0, 2, 4, 6, 8])

### Comparison

In [36]:
a > 2

array([False, False, False,  True,  True])

In [37]:
a[a > 2]

array([3, 4])

### Summaring

Creating arrays

Multi-dimensensionnal arrays

Randonly generated arrays

Element-wise operations

Comparaison operations

Logical operational