# Machine Learning Zoomcamp
## 1.9 Introduction to Pandas
Plan
- Data Frames
- Series
- Index
- Accessing elements
- Element-wise operations
- Feltering
- String operations
- Summarizing operations
- Missing values
- Grouping
- Getting the Numpy arrays

In [1]:
import pandas as pd
import numpy as np

In [46]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2007, None, 4, 'AUTAMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia', 2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340]
]

colunms = [
    'Make', 'Model', 'Year', 'Engire HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicule Style', 'MSRP'
]

In [71]:
df1 = pd.DataFrame(data, columns=colunms)

In [72]:
df1

Make     Model  Year  Engire HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2007        NaN                 4         AUTAMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicule Style   MSRP  
0          sedan   2000  
1          Sedan  27150  
2    convertible  54990  
3        4dr SUV  34450  
4         Pickup  32340

In [73]:
#df1.to_dict()

In [74]:
#df1.to_json(orient="split")

In [75]:
df1.loc[[1, 2]]

Make   Model  Year  Engire HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2007        NaN                 4         AUTAMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicule Style   MSRP  
1          Sedan  27150  
2    convertible  54990

In [76]:
df1

Make     Model  Year  Engire HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2007        NaN                 4         AUTAMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicule Style   MSRP  
0          sedan   2000  
1          Sedan  27150  
2    convertible  54990  
3        4dr SUV  34450  
4         Pickup  32340

In [80]:
df1.columns = [col.lower().replace(' ', '_') for col in df1.columns]
df1

make     model  year  engire_hp  engine_cylinders transmission_type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2007        NaN                 4         AUTAMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  vehicule_style   msrp  
0          sedan   2000  
1          Sedan  27150  
2    convertible  54990  
3        4dr SUV  34450  
4         Pickup  32340

In [82]:
df1.isnull().sum()

make                 0
model                0
year                 0
engire_hp            1
engine_cylinders     0
transmission_type    0
vehicule_style       0
msrp                 0
dtype: int64

# Home-work


## cohort 2024

In [86]:
pd.__version__

'2.3.1'

In [120]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"

In [121]:
df = pd.read_csv(url)

In [122]:
df.head(3)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   

        Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
0  ExpertBook  Intel Core i5    8      512          SSD  NaN    15.6    No   
1          Go  Intel Celeron    8      256          SSD  NaN    15.6    No   
2  ExpertBook  Intel Core i3    8      256          SSD  NaN    15.6    No   

   Final Price  
0       1009.0  
1        299.0  
2        789.0

## Q2. Records count
How many records are in the dataset?

In [123]:
len(df)

2160

## Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [124]:
df['Brand'].nunique()

27

## Q4. Missing values
How many columns in the dataset have missing values?

In [125]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

## Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [126]:
df[df['Brand'] == 'Dell']['Final Price'].max()

np.float64(3936.0)

## Q6. Median value of Screen
1- Find the median value of Screen column in the dataset.

2- Next, calculate the most frequent value of the same Screen column.

3- Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

4- Now, calculate the median value of Screen once again.

Has it changed?

> Hint: refer to existing mode and median functions to complete the task.

- Yes
- No

In [127]:
response = {}

response['value median of screen'] = df['Screen'].median()
response['value most frequent of screen'] = df['Screen'].mode()

response


{'value median of screen': np.float64(15.6),
 'value most frequent of screen': 0    15.6
 Name: Screen, dtype: float64}

In [190]:
df['Screen'].fillna(df['Screen'].mode()[0], inplace=True)
print("new median: ",  df['Screen'].median())

/tmp/ipykernel_26563/2742929951.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Screen'].fillna(df['Screen'].mode()[0], inplace=True)


new median:  15.6


In [191]:
df['Screen'].isnull().sum()

np.int64(0)

## Q7. Sum of weights
1- Select all the "Innjoo" laptops from the dataset.

2- Select only columns RAM, Storage, Screen.

3- Get the underlying NumPy array. Let's call it X.

4- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

5- Compute the inverse of XTX.

6- Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

7- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

8- What's the sum of all the elements of the result?

> Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [132]:
df[df['Brand'] == 'Innjoo']

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [133]:
df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [135]:
X = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']].values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [166]:
XT = X.T
XTX = np.dot(XT, X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [167]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [168]:
np.dot(inv_XTX,XTX)

array([[ 1.00000000e+00, -2.75571802e-13,  6.32385368e-15],
       [ 1.02488553e-16,  1.00000000e+00,  8.14222656e-17],
       [-7.04660473e-16, -2.84062325e-14,  1.00000000e+00]])

In [169]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [171]:
w_int = np.dot(inv_XTX, XT)
w = np.dot(w_int, y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [172]:
print(w.sum())

91.2998806299555


## cohort 2023

In [175]:
url2 = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"

In [176]:
df2 = pd.read_csv(url2)
df2.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY

## Question 2
How many columns are in the dataset?

In [177]:
len(df2.columns)

10

## Question 3
Which columns in the dataset have missing values?

In [178]:
df2.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

## Question 4
How many unique values does the ocean_proximity column have?

In [179]:
df2["ocean_proximity"].nunique()

5

## Question 5
What's the average value of the median_house_value for the houses located near the bay?

In [183]:
df2[df2['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean().round()

np.float64(259212.0)

## Question 6
1- Calculate the average of total_bedrooms column in the dataset.

2- Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.

3- Now, calculate the average of total_bedrooms again.

4- Has it changed?

Has it changed?

> Hint: take into account only 3 digits after the decimal point.

* Yes
* No

In [184]:
df2['total_bedrooms'].mean()

np.float64(537.8705525375618)

In [192]:
df2['total_bedrooms'].fillna(df2['total_bedrooms'].mean(), inplace=True)
df2.isnull().sum()

/tmp/ipykernel_26563/1718901957.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['total_bedrooms'].fillna(df2['total_bedrooms'].mean(), inplace=True)


longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [193]:
df2['total_bedrooms'].mean()

np.float64(537.8705525375617)

In [194]:
print('No, changing')

No, changing


## Question 7
1- Select all the options located on islands.

2- Select only columns housing_median_age, total_rooms, total_bedrooms.

3- Get the underlying NumPy array. Let's call it X.

4- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

5- Compute the inverse of XTX.

6- Create an array y with values [950, 1300, 800, 1000, 1300].

7- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

8- What's the value of the last element of w?

> Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [200]:
df2[df2['ocean_proximity'] == 'island'.upper()]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [212]:
X2 = df2[df2['ocean_proximity'] == 'island'.upper()][['housing_median_age', 'total_rooms', 'total_bedrooms']].values

X2

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [213]:
TX2 = X.T
XTX2 = np.dot(TX, X)

XTX2

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [214]:
inv_XTX2 = np.linalg.inv(XTX2)

inv_XTX2

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [215]:
y2 = np.array([950, 1300, 800, 1000, 1300])

y2

array([ 950, 1300,  800, 1000, 1300])

In [216]:
w_int2 = np.dot(inv_XTX2, TX2)

w2 = np.dot(w_int2, y2)

w2

array([23.12330961, -1.48124183,  5.69922946])

In [220]:
print(w2[-1].round(4))

5.6992


In [13]:
!git add pandas.ipynb
!git commit -m "pandas traininng"
!git push

On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/

nothing added to commit but untracked files present (use "git add" to track)
Everything up-to-date


In [14]:
#!pip install jupyterlab-commenting-service
#!jupyter labextension install @jupyterlab/commenting-extension

